import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header";
import "./globals.css";

const brandFont = localFont({
  src: "./fonts/custom-brand-font.woff2",
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`min-h-full flex flex-col ${brandFont.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
